FROM python:3.11-slim

WORKDIR /app

COPY serving/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/ ./src/
COPY serving/ ./serving/
COPY models/ ./models/

ENV MODEL_PATH=/app/models/loan_propensity_rf.joblib
ENV PYTHONPATH=/app

EXPOSE 8000

CMD ["uvicorn", "serving.app:app", "--host", "0.0.0.0", "--port", "8000"]
